### ISSUE TITLE
Loss of Connection with Wireless Use

### ISSUE THREAD

**Issue by ChrisTMChen** [ScottMit/HCI-Mobile#5]
Bluefruit loses connection or fails to function properly when using the battery and not plugged into a computer.

**Comment by Laura-Maisy** [comment]
Deleted the following from the code:

// while (!Serial);  // wait for Serial to startup - maybe don't need this?
  delay(500);

**Comment by ScottMit** [comment]
This line should be removed when you disconnect the feather from the computer.
Serial communication with the computer appears to be effected when it is removed. So you may want to put it back when developing code with the serial monitor.
